databases:
- name: my-flickr-to-google-photos-db
  region: frankfurt
  ipAllowList: []

services:
 - type: web
   region: frankfurt
   name: my-flickr-to-google-photos
   env: docker
   dockerfilePath: ./Dockerfile.render
   autoDeploy: false
   envVars:
     - key: DB_HOST
       fromDatabase:
         name: my-flickr-to-google-photos-db
         property: host
     - key: DB_NAME
       fromDatabase:
         name: my-flickr-to-google-photos-db
         property: database
     - key: DB_USERNAME
       fromDatabase:
         name: my-flickr-to-google-photos-db
         property: user
     - key: DB_PASSWORD
       fromDatabase:
         name: my-flickr-to-google-photos-db
         property: password
     - key: FLICKR_KEY
       sync: false
     - key: FLICKR_SECRET
       sync: false
     - key: GOOGLE_CLIENT_ID
       sync: false
     - key: GOOGLE_CLIENT_SECRET
       sync: false
